# Generated by Django 4.2.11 on 2024-04-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HangmanGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chosen_word", models.CharField(max_length=50)),
                ("chosen_hint", models.CharField(max_length=50)),
                ("word_length", models.IntegerField()),
                ("lives", models.IntegerField(default=6)),
                ("display", models.CharField(max_length=50)),
            ],
        ),
    ]
