# Generated by Django 4.2.11 on 2024-04-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
